
#prod:
default:
  is_debug: false
  mysql_host: 8.146.211.133
  mysql_port: 3306
  mysql_db: hotel_base_info
  mysql_name: devices_library
  mysql_username: bystest
  mysql_password: bystest
  logging: /config/logging.yaml

  path: https://api.xlt-trip.com

  admin_url81: https://api.xlt-trip.com
  admin_url: https://api.xlt-trip.com

  spa_url: https://api.xlt-trip.com
